### ISSUE TITLE
Optimization of NSIndexSet.enumerate(batchSize: Int)

### ISSUE THREAD

**Issue by klefevre** [snipsco/Postal#12]
**Problem:**
We have to optimize the `NSIndexSet.enumerate(batchSize: Int)` because of too much complexity in it -> O(n)

**Example:**
If we try to fetch all emails we would do something like:
```swift
let range = NSRange(location: 1, length: Int.max - 1)
let indexSet = NSIndexSet(indexesInRange: range)

var results = [FetchResult]()
try imapSession.fetchMessages("INBOX", set: IMAPIndexes.indexes(indexSet), flags: [ .fullHeaders ]) { _ in }
```

**Current result:**
It takes too much time for a provider that have a `batchSize == Int.max` to create the only one indexset needed for the fetch.

**Expected result:**
Instant fetch

**Possible solution:**
We could try to use the `Strideable` protocol instead or simply optimize inside the method.

**Comment by jeremiegirault** [comment]
Is it really an issue ? because we have to generate a libetpan set afterwards. Having an infinite set is the base issue.

**Comment by klefevre** [comment]
Agree but the problem still remains with the actual API.
