### ISSUE TITLE
Question: How do I move or delete a message?

### ISSUE THREAD

**Issue by matadan** [snipsco/Postal#19]

**Comment by jeremiegirault** [comment]
Good question. Postal does not have this feature yet, I guess it would be a great addition cc @klefevre 
I guess libetpan will have such imap feature, we should make it available to swift.
Any help is welcome !

**Comment by matadan** [comment]
I've looked into this...

To DELETE a message you need to set the .deleted flag in the message's flags and then EXPUNGE the folder.
To MOVE a message you need to copy it to the new folder and then DELETE it from the old folder unless MOVE is supported.

I've been able to do this with Mailcore before so it is supported by libetpan but I'm not familiar enough with Postal to modify it yet.

**Comment by jeremiegirault** [comment]
#20 implements the move command.
Still needs the delete one.

**Comment by matadan** [comment]
Great. You guys are fast! I'm doing this in my spare time so I will pull the changes and test it out and feedback any issues if I find any. But may take me a few days.
