### ISSUE TITLE
Question: fetching data from body.mailParts

### ISSUE THREAD

**Issue by loicwolff** [snipsco/Postal#24]
Is there a way to check if an email body contains text/html and fallback to fetching plain/text?

**Comment by jeremiegirault** [comment]
@loicwolff Yes: You have to fetch a first time the bodyStructure only (not the body contents).
You can then iterate on mailParts in order to find the text/plain inline attachment part and you can then fetch this attachment using the partId. @klefevre can you help with the method names ?
