### ISSUE TITLE
Gmail requiring OAuth2 

### ISSUE THREAD

**Issue by ajbraus** [snipsco/Postal#26]
Looks like Gmail requires using OAuth2, otherwise the user has to set their gmail account to be accessible by "less secure" apps. ...

**Comment by klefevre** [comment]
Postal provide a way to connect to Gmail using OAuth2 (but also Yahoo).
All you have to do is:
`let postal = Postal(configuration: .gmail(login: "foobar@gmail.com", password: .accessToken("_YOU_ACCESS_TOKEN")`

**Comment by jeremiegirault** [comment]
Hey @ajbraus !
This quirk is referenced in this document: https://github.com/snipsco/Postal/blob/master/Documentation/ProviderQuirks.md

Postal deliberately does not handle oauth. Our goal is that it could be used even on servers, therefore we do not assume the way you will obtain your access token.
It's your responsibility to use a swift oauth framework or to create a web flow to obtain the access token that you need

**Comment by ajbraus** [comment]
Great thx!
