### ISSUE TITLE
How know encode type when I parse content a mail?

### ISSUE THREAD

**Issue by khacdai37** [snipsco/Postal#39]
I have created a mail app using Postal Framework and my mail server send the message to app with different type data, so how I know a data in body is encode/decode by type?
In my example I don't know data should encode with `NSUTF8StringEncoding` or `NSISO2022JPStringEncoding` :(

```swift
msg.body?.allParts.forEach({ (singlePart) in
    let meesage = String.init(data: (singlePart.data?.rawData)!, encoding: NSUnicodeStringEncoding)
    if singlePart.mimeType == MimeType.textPlain {
        mailInfo.messageDescription = meesage?.stringByTrimmingCharactersInSet(NSCharacterSet.whitespaceAndNewlineCharacterSet()) ?? ""
    } else if singlePart.mimeType == MimeType.textHtml {
        mailInfo.message = meesage ?? ""
    }
})
```

Thanks for support!

**Comment by klefevre** [comment]
Sadly Postal give you only a few encoding type as referred here: https://github.com/snipsco/Postal/blob/fad90b6a8f8dd2cbb9002f9823c43ef99bbc21ae/Postal/ContentEncoding%2BParsing.swift#L28 .

It's clearly an issue and I suggest you to try to find the encoding type manually. If using `NSString` isn't an issue for you I suggest you to use the method `NSString.stringEncoding(for:encodingOptions:convertedString:usedLossyConversion:)`. 
Documentation here: https://developer.apple.com/reference/foundation/nsstring/1413576-stringencoding
