### ISSUE TITLE
fetchMessages attempts to fetch 1 additional message (fetchLast fails with .undefined)

### ISSUE THREAD

**Issue by matadan** [snipsco/Postal#44]
It appears that giving an IndexSet to fetchMessages() with a single index actually tries to fetch 2 messages. This also means that fetchLast() fails.

i.e.

```
   let indexset = IndexSet(integer: 2750)
   postal.fetchMessages("INBOX", uids: indexset, flags: [ .fullHeaders ], ...
```

actually tries to fetch messages 2750 and 2751.

**Comment by klefevre** [comment]
Interesting... thank for the report. Could you you just tell me which mail provider you are on ?

**Comment by matadan** [comment]
I'm testing with iCloud.

**Comment by matadan** [comment]
I think it might be possible because **IndexSet.unreleasedMailimapSet(**) includes the upperBound in the Range but the range is 2750..<2751 so should not include the upperBound.

Could it be that it does not know the difference between 1...2 and 1..<2 ranges?

**Comment by matadan** [comment]
I think that fixed it. I'll submit a PR.

**Comment by klefevre** [comment]
You're right the conversion between `IndexSet` and `mailimap_set` is wrong.

**Comment by matadan** [comment]
I have submitted a PR.
