### ISSUE TITLE
Gmail OAuth2 error

### ISSUE THREAD

**Issue by likedan** [snipsco/Postal#50]
I've implemented Gmail Outh2 and pass the access token in. It got this error: error: login("Invalid credentials (Failure)")

**Comment by jeremiegirault** [comment]
Have you set the correct scope as in https://github.com/snipsco/Postal/blob/master/Documentation/ProviderQuirks.md#gmail ?
The scope is `https://mail.google.com/`

**Comment by likedan** [comment]
Thanks for the quick reply! Where should I set the scope? An example?

**Comment by jeremiegirault** [comment]
You should set the scope when you present the oauth flow to the user (in a scope GET parameter usually).

**Comment by likedan** [comment]
Emmm, I'm not sure if we're on the same page, but I've done the google Oauth2 flow  and successfully retrieved the access token, but can connect with postal. I was doing let postal = Postal(configuration: .gmail(login: GIDSignIn.sharedInstance().currentUser.profile.email, password: PasswordType.accessToken(access_token)))

Kedan

发自我的 iPhone

**Comment by jeremiegirault** [comment]
okay, what scope have you used during oauth flow ?

**Comment by likedan** [comment]
Got it to work! Accidentally figured out where to add the scope. 

Thanks for the assistance,

Kedan
