### ISSUE TITLE
postal.logger statement doesn't compile

### ISSUE THREAD

**Issue by ikemuc** [snipsco/Postal#51]
Hi klevefre,

you wrote about debugging Postal:

> You can set a closure on a Postal instance to have IMAP logs:
>     let postal = Postal(configuration: ...)
>     postal.logger { log in
>         print(log)
>     }

Unfortunately this doesn't work in my code.
I get the compiler error message "**Cannot call value of non-function type 'logger?**'

This is my code:

    init(hostname: String, userName: String, password: String) {
        log.debug("init called...")
        
        configuration = Configuration(hostname: hostname, port: 993, login: userName, password: .plain(password), connectionType: .tls, checkCertificateEnabled: false)
        
        let postal: Postal = Postal(configuration: configuration)
        postal.logger { log in
            print(log)
        }
    [...]

What's wrong with my code? It's exactly as you wrote...?

**Comment by klefevre** [comment]
I'm sorry i've made a typo it's:

```swift
let postal = Postal(configuration: ...)
postal.logger = { log in
    print(log)
}
```
