### ISSUE TITLE
Question: Can I use Postal to reference another email provider?

### ISSUE THREAD

**Issue by RandyHBH** [snipsco/Postal#57]
I would like to set my email provaider diferent then gmail, yahoo, etc. There is a way to this using Postal?

**Comment by klefevre** [comment]
Sure you just a to setup a `let my_custom_config = Configuration(hostname: ..., etc`. Then instantiate a Postal instance normally: `let postal = Postal(configuration: my_custom_config)`

**Comment by RandyHBH** [comment]
Great. Can you privide me the link to the documentation, i can find it??

**Comment by klefevre** [comment]
We don't have a proper documentation but we have documented every public functions. We though is was good enough since the API is quite simple.

**Comment by RandyHBH** [comment]
Hello again, and great job with postal by the way, I've been searching how to send a message, but i can't find a way, is this a missing feature??

**Comment by klefevre** [comment]
Postal doesn't support sending messages. It's because Postal is only an IMAP client, it's means you can only read or modify messages.
If you need to send messages you'll need a SMPT client. You may need to check out mailcore for this.

**Comment by RandyHBH** [comment]
Postal will support SMTP in a near future?? it will be a nice feature ;)

**Comment by klefevre** [comment]
Postal won't support this feature because we just don't have time to work on it.
