### ISSUE TITLE
iCloud authentication for an account that uses two-factor

### ISSUE THREAD

**Issue by Timstarockz** [snipsco/Postal#59]
Is it possible to sign in to an icloud account that has two-factor auth enabled?

**Comment by jeremiegirault** [comment]
Hi @Timstarockz, IIRC we tried to do this and had to use an app-specific password, see the https://github.com/snipsco/Postal/blob/master/Documentation/ProviderQuirks.md document

**Comment by jeremiegirault** [comment]
If you find another way to login a 2fa-enabled iCloud account, feel free to submit a PR ! This solution does not feel optimal but is the only one publicly-documented.
