### ISSUE TITLE
What is the API to get the text content of an email?

### ISSUE THREAD

**Issue by tlkahn** [snipsco/Postal#73]
It was asked here by someone: https://stackoverflow.com/questions/41155748/how-get-mail-content-using-postal-swift-framework

Please let me know if there are any document or dev guide to start? Or how to find out?

**Comment by jeremiegirault** [comment]
Hi, instead of using `rawData` I invite you to look at `decodedData` : https://github.com/snipsco/Postal/blob/master/Postal/MailData%2BDecode.swift#L29
