### ISSUE TITLE
Asynchronous acquisition of attachments when fetchMessage .body

### ISSUE THREAD

**Issue by owlems** [snipsco/Postal#74]
我只想获取邮件 的主体内容  如果附件太大会加载很慢的问题.  可以改成手到的吗.

**Comment by jeremiegirault** [comment]
I used google translate:
```
I just want to get the main content of the message if the attachment is too big to load a very slow problem.
```

Would it be possible to use English for issue please ? It would be easier for us.

If I remember correctly, you are able to download the structure of the message first and choose the attachment you need afterwards. You don't need to download all attachments at once

**Comment by owlems** [comment]
When I use the structure can not get the contents of the message

My current problem is that there is a mail there is a 300MB attachment is loaded for a long time before you can display the contents of the message

I mean that the contents of the e-mail and attachments are separated

**Comment by jeremiegirault** [comment]
Hmm We may have encountered this issue in the past. @klefevre do you remember how we handled this use case ?

**Comment by owlems** [comment]
@jeremiegirault   #24  


Hi, I saw this.
<img width="874" alt="wx20171008-220423 2x" src="https://user-images.githubusercontent.com/32491968/31317510-dc2c0e34-ac74-11e7-890a-303de27bbaa0.png">

I use the attachment to get the content after the data processing to use what?
Can you give me a demo?

thank you very much

**Comment by carping** [comment]
@jeremiegirault   
Hello, I've got this problem too.
The problem of data parsing is not correct
