### ISSUE TITLE
"Use of extraneous '&'" error when building for iOS 12

### ISSUE THREAD

**Issue by Fri3ndlyGerman** [snipsco/Postal#80]
When compiling a project with Postal installed via CocoaPods, the build fails in `Extensions+Parsing.swift` with error `Use of extraneous '&'` in lines 51, 55, 60 and 64

**Comment by klefevre** [comment]
hey @Fri3ndlyGerman thanks for the pointing this out. I don't have time to fix this issue now. If you want a quick fix you can post PR and I'll merge it quickly and will perform a release in the mean time.
Otherwise it'll have to wait a bit...

**Comment by Fri3ndlyGerman** [comment]
Never mind, the issue is gone in the new beta (Xcode 10 beta 4), thanks for your time anyway
